---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2021-02-12b
  commands:
    - export LANG=en_US.UTF-8
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j2
    - env TERM=xterm ctest
